### ISSUE TITLE
Extend flist tooling

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/0-flist#13]
`zflist` CLI already greatly simplify the creation of flist.
But we want to go further and provide some tools so user can start from an existing flist, modify it, then create a new one that include his changes.

I think [libflist](https://github.com/threefoldtech/0-flist/tree/development/libflist) was started with this in mind, but I think the works has never really be finished.

I would like to also include some tools to define the metadata of a container when creating a container.
Metadata are the information about how the flist should be used (see #9):
- entry point
- volumes
- environment variables
- exposed ports

Tasks:
- [x] Metadata (https://github.com/threefoldtech/0-flist/issues/9)
- [ ] File and directories manipulation (https://github.com/threefoldtech/0-flist/issues/13)

**Comment by maxux** [comment]
We have multiple options about flist manipulations:
- Using a fuse interface (like 0-fs) which could mount the flist, you can do any filesystem operations via this fuse layer to modify the flist and when you umount the flist, you have a new one with the changes. But this require you to be root and have fuse available.
- Using a tool like `zflist` with specific options, this tool would open a staging directory with the database and you can manipulate the flist step-by-step like:
  - `zflist-edit open [flist-name] [temporary-point]`
  - `zflist-edit [temporary-point] chmod 644 /bin/hello`
  - `zflist-edit [temporary-point] rm /bin/false`
  - `zflist-edit [temporary-point] commit`

**Comment by maxux** [comment]
Metadata will be internal metadata or should be compatible with `config.json` from runc, etc ?

**Comment by zaibon** [comment]
> Metadata will be internal metadata or should be compatible with config.json from runc, etc ?

No not really. The info contains in the metadata will eventually be used to generate part of a config.json used to start a container. But the format of the metadata doesn't need to be compliant with OCI spec.

**Comment by maxux** [comment]
Here is a PoC of the new `zflist-edit` tool. It works as described.
Right now, only `open`, `chmod` and `close` is implemented.

Original mode (`-rw-r--r--`)
```
$ zflist --archive /tmp/debug.flist --list | grep World
-rw-r--r--  maxux    maxux           6 (   1 blocks) World
```

Update the flist
```
$ zflist-edit open /tmp/debug.flist 
$ zflist-edit chmod 705 /home/maxux/Desktop/directory1/World
$ zflist-edit commit /tmp/newdebug.flist
```

Checking new mode (`-rwx---r-x`)
```
$ zflist --archive /tmp/newdebug.flist --list | grep World
-rwx---r-x  maxux    maxux           6 (   1 blocks) World
```

**Comment by maxux** [comment]
- `chmod` updated and use correct api calls
- `rm` is implemented (only remove files), and use correct api calls

The api was changed and fixed to handle « nice edit-and-commit » changes usable in two lines, all the others operations can now use theses features to dramatically simplify overall usage.

**Comment by maxux** [comment]
Added:
- [x] `metadata` implemented (see #9)
- [x] `ls` implemented on directory level (you can print directory contents)
- [x] `cat` implemented, you can get file contents (payload from backend)
- [x] `put` partially implemented, you can add a local file into a target directory (payload is not yet handled, but entry is well added with metadata)

Missing:
- [ ] `rmdir`: remove a directory (and contents)
- [ ] `mkdir`: create an empty directory
- [ ] `stat`: dump an inode with deep information (including chunks hashes)
- [ ] `cp`: copy a file from a directory to another directory/another name
- [ ] `mv`: move (or rename) a file (does a cp then rm source)
- [ ] `cpdir`: copy a full directory tree to another directory
- [ ] `mvdir`: move a full directory

It's better to get `rmdir`, `cpdir` and `mvdir` distinction with `rm`, `cp` and `mv` for files, because internally, directories and files are completely different implementation and it makes things more difficult to do implicit assumption for now.

**Comment by zaibon** [comment]
That looks pretty cool. It really starts to be a nice flist tool box.

I was thinking maybe we can also have a `mount` command. This command would look if 0-fs is installed and if it is, it would mount the flist. So we have a single CLI tool to do anything with an flist.

**Comment by maxux** [comment]
## Added
- [x] `rmdir`: remove a directory and subdirectories (recursive)
- [x] `mkdir`: create an empty directory
- [x] `stat`: dump an inode with deep information (including chunks hashes)

**Comment by maxux** [comment]
In order to implement `putdir` in a proper way, the way how library does the creation needs to be rethinked. It's not enough dynamic and flexible right now. More over, the library use `ftw` to read directory hierarchy, this should be moved to `fts`, which is much more secure and clean. I'm working on it.
